# Generated by Django 3.0.2 on 2020-08-29 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Height', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='身長')),
                ('Weight', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='体重')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.localtime, null=True, verbose_name='実施日')),
                ('BMI', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='BMI')),
                ('condition', models.CharField(max_length=256, verbose_name='状態')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='名前')),
            ],
        ),
    ]
